<?php

$config = new PhpCsFixer\Config();

return $config
    ->setRiskyAllowed(true)
    ->setRules([
        'align_multiline_comment' => ['comment_type' => 'phpdocs_only'],
        'array_indentation' => true,
        'binary_operator_spaces' => ['default' => 'single_space'],
        'blank_line_after_namespace' => true,
        'blank_line_after_opening_tag' => true,
        'blank_lines_before_namespace' => ['max_line_breaks' => 2, 'min_line_breaks' => 2],
        'braces_position' => ['allow_single_line_anonymous_functions' => true, 'allow_single_line_empty_anonymous_classes' => true, 'anonymous_classes_opening_brace' => 'same_line', 'anonymous_functions_opening_brace' => 'same_line', 'classes_opening_brace' => 'next_line_unless_newline_at_signature_end', 'control_structures_opening_brace' => 'same_line', 'functions_opening_brace' => 'next_line_unless_newline_at_signature_end'],
        'cast_spaces' => ['space' => 'none'],
        'class_attributes_separation' => ['elements' => ['method' => 'one', 'trait_import' => 'one']],
        'class_definition' => ['inline_constructor_arguments' => false, 'multi_line_extends_each_single_line' => false, 'single_item_single_line' => true, 'single_line' => true, 'space_before_parenthesis' => true],
        'class_reference_name_casing' => true,
        'clean_namespace' => true,
        'compact_nullable_type_declaration' => true,
        'concat_space' => ['spacing' => 'one'],
        'constant_case' => ['case' => 'lower'],
        'control_structure_braces' => true,
        'control_structure_continuation_position' => ['position' => 'same_line'],
        'declare_equal_normalize' => ['space' => 'single'],
        'declare_parentheses' => true,
        'echo_tag_syntax' => ['format' => 'long', 'long_function' => 'print', 'shorten_simple_statements_only' => false],
        'elseif' => true,
        'empty_loop_body' => ['style' => 'braces'],
        'encoding' => true,
        'full_opening_tag' => true,
        'function_declaration' => ['closure_fn_spacing' => 'none', 'closure_function_spacing' => 'none', 'trailing_comma_single_line' => false],
        'include' => true,
        'indentation_type' => true,
        'integer_literal_case' => true,
        'line_ending' => true,
        'linebreak_after_opening_tag' => true,
        'lowercase_cast' => true,
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'method_argument_space' => ['after_heredoc' => true, 'attribute_placement' => 'same_line', 'keep_multiple_spaces_after_comma' => false, 'on_multiline' => 'ensure_fully_multiline'],
        'multiline_comment_opening_closing' => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'native_function_casing' => true,
        'native_type_declaration_casing' => true,
        'new_with_parentheses' => ['anonymous_class' => true, 'named_class' => true],
        'no_alternative_syntax' => ['fix_non_monolithic_code' => false],
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_break_comment' => ['comment_text' => 'fall through'],
        'no_closing_tag' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => ['tokens' => ['attribute', 'case', 'continue', 'curly_brace_block', 'default', 'extra', 'parenthesis_brace_block', 'return', 'square_brace_block', 'switch', 'throw', 'use']],
        'no_leading_namespace_whitespace' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiple_statements_per_line' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_space_around_double_colon' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => ['positions' => ['inside', 'outside']],
        'no_trailing_comma_in_singleline' => ['elements' => ['arguments', 'array', 'array_destructuring', 'group_import']],
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_control_parentheses' => ['statements' => ['break', 'clone', 'continue', 'echo_print', 'negative_instanceof', 'others', 'yield', 'yield_from']],
        'no_whitespace_before_comma_in_array' => ['after_heredoc' => true],
        'no_whitespace_in_blank_line' => true,
        'object_operator_without_whitespace' => true,
        'operator_linebreak' => ['only_booleans' => true, 'position' => 'end'],
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_indent' => true,
        'phpdoc_scalar' => ['types' => ['boolean', 'callback', 'double', 'integer', 'real', 'str']],
        'phpdoc_summary' => true,
        'phpdoc_types' => true,
        'phpdoc_var_annotation_correct_order' => true,
        'return_type_declaration' => ['space_before' => 'none'],
        'semicolon_after_instruction' => true,
        'single_blank_line_at_eof' => true,
        'single_line_after_imports' => true,
        'single_line_comment_spacing' => true,
        'single_line_empty_body' => true,
        'single_quote' => ['strings_containing_single_quote_chars' => false],
        'single_space_around_construct' => true,
        'space_after_semicolon' => ['remove_in_empty_for_expressions' => true],
        'spaces_inside_parentheses' => ['space' => 'none'],
        'statement_indentation' => ['stick_comment_to_next_continuous_control_statement' => false],
        'strict_comparison' => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space' => true,
        'ternary_operator_spaces' => true,
        'trailing_comma_in_multiline' => ['after_heredoc' => true, 'elements' => ['arguments', 'arrays', 'match', 'parameters']],
        'trim_array_spaces' => true,
        'type_declaration_spaces' => ['elements' => ['function', 'property']],
        'types_spaces' => ['space' => 'single', 'space_multiple_catch' => 'single'],
        'unary_operator_spaces' => ['only_dec_inc' => false],
        'whitespace_after_comma_in_array' => ['ensure_single_space' => true],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->in(__DIR__),
    );
